/*
 * Copyright (c) 2022 Realsil.com.cn. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Authors: nisha_chen(nisha_chen@realsil.com.cn)
 */

package com.lw.ai.glasses.utils;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.net.Uri;
import android.os.Environment;
import android.text.TextUtils;
import android.util.Log;

import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Locale;

/**
 * A tool class is used to capture the logcat generated by the app running.
 * <p>The logcat save path: sdcard/Android/data/packageName/files/Documents/logcatSaveDir</p>
 *
 * @author xp.chen
 */
public class LogWatcher {

    public static final String TAG = "LogWatcher";

    @SuppressLint("StaticFieldLeak")
    private static volatile LogWatcher instance = null;

    private static final String LOG_FILE_PREFIX = "logcat_";
    private static final String LOG_FILE_SUFFIX = ".log";
    private static final String LOG_DIR_NAME = "saveLog";

    private String mLogDirPath;

    private Context mContext;

    private Process mLogcatProcess;

    private File mLogcatFile;

    private LogWatcher() {}

    public static LogWatcher getInstance() {
        if (instance == null) {
            synchronized (LogWatcher.class) {
                if (instance == null) {
                    instance = new LogWatcher();
                }
            }
        }
        return instance;
    }

    /**
     * Start capture the logcat generated by the app.
     */
    public void startWatch(Context context) {
        stopWatch();

        if (context == null) {
            Log.e(TAG, "start failed, input context can not be null");
            return;
        } else {
            mContext = context.getApplicationContext();
        }

        mLogDirPath = resolveLogDirPath(mContext);
        if (TextUtils.isEmpty(mLogDirPath)) {
            Log.e(TAG, "LogWatcher: can not resolve log dir path");
            return;
        }

        mLogcatFile = createNewLogFile();
        if (mLogcatFile == null) {
            Log.e(TAG, "LogWatcher: can not create new log file");
            return;
        } else {
            Log.i(TAG, "LogWatcher: log file save path >>> " + mLogcatFile.getAbsolutePath());
        }

        // Clear cache log
        try {
            Process process = Runtime.getRuntime().exec("logcat -c");
            process.destroy();
        } catch (IOException e) {
            Log.e(TAG, "execute clear log cmd fail: " + e);
        }

        final String LOGCAT_FILTER_CMD = "logcat -v time *:V | grep \"(" + android.os.Process.myPid() + ")\" -f " + mLogcatFile.getAbsolutePath();

        try {
            mLogcatProcess = Runtime.getRuntime().exec(LOGCAT_FILTER_CMD);
        } catch (IOException e) {
            Log.e(TAG, "execute record log cmd fail: " + e);
        }
    }

    /**
     * Stop capture the logcat generated by the app.
     */
    public void stopWatch() {
        if (mLogcatProcess != null) {
            mLogcatProcess.destroy();
            mLogcatProcess = null;
        }

        if (mLogcatFile != null) {
            notifySystemToScan(mContext, mLogcatFile);
        }
    }

    /**
     * Collect all LogWatcher logcat files under saveLog (including date subdirectories).
     */
    public List<File> getAllLogFiles() {
        String dirPath = mLogDirPath;
        if (TextUtils.isEmpty(dirPath) && mContext != null) {
            dirPath = resolveLogDirPath(mContext);
        }
        if (TextUtils.isEmpty(dirPath)) {
            return Collections.emptyList();
        }
        File logDir = new File(dirPath);
        if (!logDir.exists() || !logDir.isDirectory()) {
            return Collections.emptyList();
        }
        List<File> result = new ArrayList<>();
        collectLogFiles(logDir, result);
        return result;
    }

    /**
     * Collect all LogWatcher logcat files; resolves save dir from context when needed.
     */
    public List<File> getAllLogFiles(Context context) {
        if (TextUtils.isEmpty(mLogDirPath) && context != null) {
            mContext = context.getApplicationContext();
            mLogDirPath = resolveLogDirPath(mContext);
        }
        return getAllLogFiles();
    }

    /**
     * Delete all LogWatcher log files and restart capture with a fresh file.
     */
    public void clearAllLogFiles() {
        stopWatch();
        mLogcatFile = null;

        String dirPath = mLogDirPath;
        if (TextUtils.isEmpty(dirPath) && mContext != null) {
            dirPath = resolveLogDirPath(mContext);
        }
        if (!TextUtils.isEmpty(dirPath)) {
            deleteLogDirContents(new File(dirPath));
        }

        if (mContext != null) {
            startWatch(mContext);
        }
    }

    /**
     * Delete all LogWatcher log files; resolves save dir from context when needed.
     */
    public void clearAllLogFiles(Context context) {
        if (context != null) {
            mContext = context.getApplicationContext();
            if (TextUtils.isEmpty(mLogDirPath)) {
                mLogDirPath = resolveLogDirPath(mContext);
            }
        }
        clearAllLogFiles();
    }

    private static String resolveLogDirPath(Context context) {
        if (context == null) {
            return null;
        }
        String logDirPath = null;
        if (Environment.getExternalStorageState().equals(Environment.MEDIA_MOUNTED)) {
            File documentFileDir = context.getExternalFilesDir(null);
            if (documentFileDir != null) {
                logDirPath = documentFileDir.getAbsolutePath() + File.separator + LOG_DIR_NAME;
            } else {
                Log.e(TAG, "shared storage is not currently available.");
            }
        } else {
            Log.e(TAG, "shared storage is not mounted.");
        }
        if (TextUtils.isEmpty(logDirPath)) {
            logDirPath = context.getFilesDir().getAbsolutePath() + File.separator + LOG_DIR_NAME;
            Log.w(TAG, "use the app's inner save dir");
        }
        return logDirPath;
    }

    private static void collectLogFiles(File dir, List<File> out) {
        File[] children = dir.listFiles();
        if (children == null) {
            return;
        }
        for (File child : children) {
            if (child.isDirectory()) {
                collectLogFiles(child, out);
            } else if (child.isFile() && child.getName().endsWith(LOG_FILE_SUFFIX)) {
                out.add(child);
            }
        }
    }

    private static void deleteLogDirContents(File dir) {
        File[] children = dir.listFiles();
        if (children == null) {
            return;
        }
        for (File child : children) {
            if (child.isDirectory()) {
                deleteLogDirContents(child);
                child.delete();
            } else if (child.isFile() && child.getName().endsWith(LOG_FILE_SUFFIX)) {
                if (!child.delete()) {
                    Log.w(TAG, "failed to delete log file: " + child.getAbsolutePath());
                }
            }
        }
    }

    private File createNewLogFile() {
        File logSaveDir = new File(mLogDirPath, getCurrentDateStr());
        if (!logSaveDir.exists()) {
            boolean mkdirs = logSaveDir.mkdirs();
            if (!mkdirs) {
                Log.e(TAG, "LogWatcher: create new save dir failed");
                return null;
            }
        }

        String logFileName = LOG_FILE_PREFIX + getCurrentTimeStr() + LOG_FILE_SUFFIX;
        File logFile = new File(logSaveDir, logFileName);

        try {
            boolean createRet = logFile.createNewFile();
            if (!createRet) {
                Log.e(TAG, "LogWatcher: create new log file failed");
                return null;
            }
        } catch (IOException e) {
            Log.e(TAG, "create new log fail: " + e);
            return null;
        }

        return logFile;
    }

    private static String getCurrentTimeStr() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss", Locale.getDefault());
        return sdf.format(new Date(System.currentTimeMillis()));
    }

    private static String getCurrentDateStr() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        return sdf.format(new Date(System.currentTimeMillis()));
    }

    private static void notifySystemToScan(Context context, File file) {
        if (context == null || file == null) return;
        Intent intent = new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE);
        Uri uri = Uri.fromFile(file);
        intent.setData(uri);
        context.sendBroadcast(intent);
    }

}
